language: node_js
node_js:
  - "8"

script: npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $MOZART_GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
